const latexList = [
  `\\left| 2 \\right|`,
  `\\angle ABC`,
  `a\\approx b`,
  `\\bar {xy}`,
  `\\bar x`,
  `\\because a=b`,
  `a=1\\\\b=2`,
  `30℃ `,
  `45^\\circ`,
  `:`,
  `△ABC\\cong △DEF`,
  `\\cos 45^\\circ`,
  `\\cos \\angle ABC`,
  `\\cot \\angle ABC`,
  `3\\div 20`,
  `\\left\\{ \\begin{array}{l} x=1\\\\{y=2} \\end{array} \\right.`,
  `\\frac{1}{2}`,
  `\\frac{{12}}{5}`,
  `\\frac{5}{{12}}`,
  `\\frac{{12}}{{25}}`,
  `x\\ge 1`,
  `x\\le 1`,
  `x\\ne 1`,
  `AB\\parallel CD`,
  `30\\%`,
  `AB\\perp CD`,
  `3\\pi`,
  `\\pm 1`,
  `\\overset{\\frown}{{AB}}`,
  `\\overset{\\frown}{A}`,
  `△ABC\\sim △DEF`,
  `\\sqrt 2`,
  `\\sqrt {12}`,
  `\\sqrt [3]{2}`,
  `a^2`,
  `a^{xy}`,
  `(xy)^2`,
  `a^{xy}b`,
  `a_1`,
  `a_{10}`,
  `a_1b_1`,
  `a_{12}b_{12}`,
  `\\therefore x=1`,
  `a\\times b`,
  `xy\\times ab`,
  `△ABC`,
  `\\vec a`,
  `\\vec {AB}`,
]

module.exports = latexList
